### ISSUE TITLE
Dynamic parameters gripper

### ISSUE THREAD

**Issue by jonasspring** [justagist/franka_panda_description#2]
Hi,
I was wondering were you took the dynamic parameters from the gripper from, because they
are not identified in the referenced paper. Do you know how accurate these values are compared to the real gripper?
Thanks a lot for the help.

**Comment by justagist** [comment]
These parameters are not realistic and are purely for simulation purposes. They are probably not at all close to those of the real gripper. Recent updates in the description had attempted to simulate the motion of the gripper fingers of the real robot, but not much time has been spent on fixing the dynamics of the gripper.
Sorry about that.
If you do manage to find a reasonably good set of parameters or know of a way to estimate them, please let me know or post a PR.
-- Saif
